### ISSUE TITLE
Module prints data instead of returning it from an instance method.

### ISSUE THREAD

**Issue by vivekjoshy** [cryzed/Python-Omegle-API#2]
There are numerous print statements spread out in the file. This can cause issues when writing GUI's and event driven programs.

I recently tried to implement this as a GUI and found it impossible to do.

**Comment by cryzed** [comment]
I'm surprised this still works at all. You are supposed to provide your own event handlers (check the examples), which don't include those print-statements; the default ones are just there to get up and running quickly.

If you see any output on stdout after doing so, it's because of `Client._handle_event`, which is indicative of a bigger problem: Incompatibility with the unofficial API after 3 years. I wouldn't recommend using this module anymore, you should check around for some other API wrapper.

**Comment by vivekjoshy** [comment]
I should have payed attention to the examples. My Bad.
But are you saying that even if i provide handlers it might still malfunction ?

**Comment by cryzed** [comment]
Yes, the code is 3 years old and was more a proof-of-concept back then, and I'm sure that Omegle has since changed many things, most likely also with the intention of making life harder for people who want to write these unofficial API wrappers.

Your best bet is to find another up-to-date Python module that does the same or possibly write one yourself. Sorry!

**Comment by vivekjoshy** [comment]
Yeah I guess i would have to write one myself. I was also surprised it still worked after 3 years. Never even got detected as a bot once, unlike a lot of the "API's" I used before this one.

**Comment by cryzed** [comment]
If I can give you some tips: You might want to try using [Charles](https://www.charlesproxy.com/) to analyze the traffic sent between your browser and Omegle. Also nowadays it would be best if you simply used [requests](http://docs.python-requests.org/en/master/), mechanize was overkill back then and is outdated now. Python 3 is also a good idea if you are up for that!

PS: If for some reason you think you need the functionality of mechanize after all (since it does some neat stuff which requests can't, i.e. automatic parsing, handling and submitting of forms), you can try either [MechanicalSoup](https://github.com/hickford/MechanicalSoup) or [robobrowser](https://github.com/jmcarp/robobrowser) which are the modern equivalents to mechanize.

If you are familiar with async Python code, checking out [aiohttp](http://aiohttp.readthedocs.io/en/stable/) might also be an option.

**Comment by vivekjoshy** [comment]
Thanks a lot. I'll be sure to ping you when I'm done.

**Comment by cryzed** [comment]
Awesome, good luck :)!
